sonar.projectKey=Heretek-AI_llama-builds
sonar.organization=heretek-ai
sonar.projectName=llama-builds
sonar.sources=src
sonar.tests=tests


sonar.python.coverage.reportPaths=coverage.xml

sonar.sourceEncoding=UTF-8
